#lang racket
(define (div-terms L1 L2)
  (if (empty-termlist? L1)
      (list (the-empty-termlist) (the-empty-termlist))
      (let ((t1 (first-term L1))
            (t2 (first-term L2)))
        (if (> (order t2) (order t1))
            (list (the-empty-termlist) L1)
            (let ((new-c (div (coeff t1) (coeff t2)))
                  (new-o (- (order t1) (order t2))))
              (let ((rest-of-result
                     (div-terms (sub-terms L1 (mult-term-by-all-terms (make-term new-c new-o) L2)) L2)))
                (if (=zero? L1) (list '0 '0)
                    (cons (adjoin-term (make-term new-c new-o) (car rest-of-result)) (cdr rest-of-result)))
              ))))))